# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the fingerprint drivers.
#

ccflags-y += -I$(srctree)/drivers/misc/mediatek/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat

obj-$(CONFIG_FPC_FINGERPRINT_STANDALONE)	+= fpc_mtk_spi.o
