snd-soc-aw883xx-objs += aw883xx_device.o
snd-soc-aw883xx-objs += aw883xx_spin.o
snd-soc-aw883xx-objs += aw883xx_monitor.o
snd-soc-aw883xx-objs += aw883xx_bin_parse.o
snd-soc-aw883xx-objs += aw883xx_calib.o
snd-soc-aw883xx-objs += aw883xx_pid_2049_init.o
snd-soc-aw883xx-objs += aw883xx_pid_2066_init.o
snd-soc-aw883xx-objs += aw883xx_pid_2183_init.o
snd-soc-aw883xx-objs += aw883xx_init.o
snd-soc-aw883xx-objs += aw883xx.o

obj-$(CONFIG_SND_SMARTPA_AW883XX) += snd-soc-aw883xx.o
